#!/usr/bin/env python


"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 0.9.16
 Generation time: Sat Jun  4 12:48:00 2005
   Source file: OrderStatusII.tmpl
   Source file last modified: Sat Jun  4 12:47:52 2005
"""

__CHEETAH_genTime__ = 'Sat Jun  4 12:48:00 2005'
__CHEETAH_src__ = 'OrderStatusII.tmpl'
__CHEETAH_version__ = '0.9.16'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromFrameOrSearchList
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Skeleton import Skeleton

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class OrderStatusII(Skeleton):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        Skeleton.__init__(self, *args, **KWs)

    def title(self,
            order,
            trans=None,
            dummyTrans=False,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time):


        """
        Generated from #def title($order) at line 4, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('Status for order #')
        write(filter(VFFSL(SL,"order.id",True), rawExpr='$order.id')) # from line 5, col 19.
        write('\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def body(self,
            trans=None,
            dummyTrans=False,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time):


        """
        Generated from #def body at line 8, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('<p>\n')
        if (VFN(VFFSL(SL,"order",True),"hasShipped",False)()):
            write(' Your order has shipped. Your tracking number is ')
            write(filter(VFFSL(SL,"order.trackingNumber",True), rawExpr='$order.trackingNumber')) # from line 11, col 50.
            write('.\n')
        else:
            write(' Your order has not yet shipped.\n')
        write('</p>\n\n<p>Order #')
        write(filter(VFFSL(SL,"order.id",True), rawExpr='$order.id')) # from line 17, col 11.
        write(' contains the following items:</p>\n<ul>\n')
        for purchased, quantity in VFN(VFFSL(SL,"order.purchased",True),"items",False)():
            write(' <li>')
            write(filter(VFFSL(SL,"purchased.name",True), rawExpr='$purchased.name')) # from line 20, col 6.
            write(': ')
            write(filter(VFFSL(SL,"quantity",True), rawExpr='$quantity')) # from line 20, col 23.
            write(' unit')
            if (VFFSL(SL,"quantity",True) != 1):
                write('s\n')
            write(' </li>\n')
        write('</ul>\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def writeBody(self,
            trans=None,
            dummyTrans=False,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time):


        """
        This is the main method generated by Cheetah
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('\n\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    _mainCheetahMethod_for_OrderStatusII= 'writeBody'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    OrderStatusII().runAsMainProgram()

