#!/usr/bin/env python


"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 0.9.16
 Generation time: Sat Jun  4 12:48:00 2005
   Source file: Skeleton.tmpl
   Source file last modified: Sat Jun  4 12:38:00 2005
"""

__CHEETAH_genTime__ = 'Sat Jun  4 12:48:00 2005'
__CHEETAH_src__ = 'Skeleton.tmpl'
__CHEETAH_version__ = '0.9.16'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromFrameOrSearchList
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class Skeleton(Template):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        Template.__init__(self, *args, **KWs)

    def respond(self,
            trans=None,
            dummyTrans=False,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time):


        """
        This is the main method generated by Cheetah
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('<html>\n<head><title>')
        write(filter(VFFSL(SL,"title",False)(VFFSL(SL,"order",True)), rawExpr='$title($order)')) # from line 2, col 14.
        write('</title></head>\n<body>\n<p>[You are logged in as ')
        write(filter(VFN(VFFSL(SL,"user",True),"getFullName",False)(), rawExpr='$user.getFullName()')) # from line 4, col 26.
        write('.]</p>\n')
        write(filter(VFFSL(SL,"body",True), rawExpr='$body')) # from line 5, col 1.
        write('''
<hr />
Online Store v1.0.
</body>
</html>
''')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    __str__ = respond

    _mainCheetahMethod_for_Skeleton= 'respond'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    Skeleton().runAsMainProgram()

