
/*
*/
// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class ClassInfo {
    public  variant className;
    public  variant packagePath;
    public  variant lowerClassName;
    public  AClassAttribute classAttributeList = new AClassAttribute();
    public void __init__() {
    }
    public void setAttributes() {
    }
    public void setLowerClassNameIndex0() {
    }
    public void addClassAttributeList() {
    }
}
