
/*
*/
// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class ClassAttribute {
    public  variant attributeName;
    public  variant attributeType;
    public  variant upperNameIndex0;
    public void __init__() {
    }
    public void setUpperNameIndex0() {
    }
}
