
/*
*/
// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class Constants {
    public  variant INPUT_DIR;
    public  variant OUT_DIR;
    public  variant TEMPLATE_DIR;
    public  variant VO_TEMPLATE;
    public  variant GET_SET_METHOD_TEMPLATE;
    public  variant PROPERTY_XML_FILE_DIR;
    public void __init__() {
    }
}
