
/*
*/
// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class XmlParser {
    public void parseXml() {
    }
    public void parseClassInfo() {
    }
    public void parseClassAttribute() {
    }
}
